E-FirmaElect-Demo/Controllers/FirmaElectronicaController.cs
using E_FirmaElect_Demo.Models;
using SIGPLUSLib;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;

namespace E_FirmaElect_Demo.Controllers
{
    public class FirmaElectronicaController : Controller
    {
        // GET: FirmaElectronica
        public ActionResult Index()
        {
            FirmaElectronicaModel oFirmaElectronicaModel = new FirmaElectronicaModel();
            oFirmaElectronicaModel.oPersona = new Entidades.Persona_BE();
            oFirmaElectronicaModel.oPersona.DNI = "46258239";
            return View(oFirmaElectronicaModel);
        }
        [HttpPost]
        public JsonResult Index(FirmaElectronicaModel oFirmaElectronicaModel)
        {

            String Resultado = "";
            String vNuevoSigString = "";
            String pRutaArchivo = string.Concat(System.Web.Hosting.HostingEnvironment.MapPath("~/DocumentosGenerados/"), "Firma_Electrina" + oFirmaElectronicaModel.oPersona.DNI + ".pdf");


            SIGPLUSLib.SigPlus oSigPlus = new SIGPLUSLib.SigPlus();
            oSigPlus.InitSigPlus();
            oSigPlus.SigCompressionMode = 0;
            oSigPlus.SigString = oFirmaElectronicaModel.oFirmaElectronica.SIGSTRING;

            Obtener_Pdf_CC(pRutaArchivo,oFirmaElectronicaModel,oFirmaElectronicaModel.oFirmaElectronica.SIGSTRING);

            oSigPlus.EncryptionMode = 0;
            oSigPlus.AutoKeyData = pRutaArchivo;
            oSigPlus.AutoKeyFinish();
            oSigPlus.EncryptionMode = 2;
            oSigPlus.SigCompressionMode = 4;

            vNuevoSigString = oSigPlus.SigString;
            oFirmaElectronicaModel.oFirmaElectronica.SIGSTRING_ENCRIPTADA = vNuevoSigString;
            oFirmaElectronicaModel.Resultado = "Ok";

            return Json(oFirmaElectronicaModel, JsonRequestBehavior.AllowGet);
        }
        #region FIRMA DIGITAL
        public Boolean Obtener_Pdf_CC(String pRutaArchivo, FirmaElectronicaModel oFirmaElectronicaModel, String pImg64)
        //Fin E.Z. 13/05/2016
        {
            Boolean b_Resultado = false;
            iTextSharp.text.Document oDocument = null;
            iTextSharp.text.pdf.PdfWriter oPdfWriter = null;
            iTextSharp.text.pdf.PdfContentByte oPdfContentByte = null;
            iTextSharp.text.Chunk oChunk = null;
            iTextSharp.text.HeaderFooter oFooter = null;
            try
            {

                using (FileStream fs = new FileStream(pRutaArchivo, FileMode.Create, FileAccess.Write))
                    {
                        // Crear PDF
                        oDocument = new iTextSharp.text.Document(iTextSharp.text.PageSize.A4, 30, 30, 15, 25);
                        oPdfWriter = iTextSharp.text.pdf.PdfWriter.GetInstance(oDocument, fs);

                        oDocument.Open();
                        oPdfContentByte = oPdfWriter.DirectContent;
                        oPdfContentByte.Stroke();
                        oPdfContentByte.SetLineWidth(0.2f);

                        oDocument.Add(Obtener_Logos(null));
                        oDocument.Add(Obtener_Blanco());
                        oDocument.Add(Obtener_Titulo("098923"));
                        oDocument.Add(Obtener_Blanco());
                        oDocument.Add(Obtener_Cliente(oFirmaElectronicaModel));
                        oDocument.Add(Obtener_Blanco());
                        oDocument.Add(Obtener_Cuenta(oFirmaElectronicaModel));
                        oDocument.Add(Obtener_Blanco());
                        oDocument.Add(Obtener_Solicitud(oFirmaElectronicaModel, "ARamirez"));
                        oDocument.Add(Obtener_Blanco());
                        oDocument.Add(Obtener_Blanco());
                        oDocument.Add(Obtener_Pie(oFirmaElectronicaModel));
                        #region "Firma"
                        //Firma 1
                        //oPdfContentByte.Rectangle(59f, 40.5f, 300f, 72.5f);
                        oPdfContentByte.BeginText();
                        oPdfContentByte.SetFontAndSize(iTextSharp.text.pdf.BaseFont.CreateFont(iTextSharp.text.pdf.BaseFont.HELVETICA_BOLD, iTextSharp.text.pdf.BaseFont.WINANSI, iTextSharp.text.pdf.BaseFont.NOT_EMBEDDED), (float)8);
                        oPdfContentByte.ShowTextAligned(iTextSharp.text.Element.ALIGN_BASELINE, "Asesor de Servicio al Cliente Finantienda", 59f, 122.5f, 0);
                        oPdfContentByte.EndText();
                        oPdfContentByte.Stroke();
                        oPdfContentByte.BeginText();
                        oPdfContentByte.SetFontAndSize(iTextSharp.text.pdf.BaseFont.CreateFont(iTextSharp.text.pdf.BaseFont.HELVETICA, iTextSharp.text.pdf.BaseFont.WINANSI, iTextSharp.text.pdf.BaseFont.NOT_EMBEDDED), (float)8);
                        oPdfContentByte.ShowTextAligned(iTextSharp.text.Element.ALIGN_BASELINE, "Cesar Mariñoas Asmat", 59f, 102.5f, 0);
                        oPdfContentByte.EndText();
                        oPdfContentByte.Stroke();
                         
                        oPdfContentByte.Rectangle(385.5f, 40.5f, 150f, 72.5f);
                        oPdfContentByte.BeginText();
                        oPdfContentByte.SetFontAndSize(iTextSharp.text.pdf.BaseFont.CreateFont(iTextSharp.text.pdf.BaseFont.HELVETICA_BOLD, iTextSharp.text.pdf.BaseFont.WINANSI, iTextSharp.text.pdf.BaseFont.NOT_EMBEDDED), (float)8);
                        oPdfContentByte.ShowTextAligned(iTextSharp.text.Element.ALIGN_BASELINE, "Firma del Cliente Titular", 430.5f, 122.5f, 0);
                        oPdfContentByte.EndText();
                        oPdfContentByte.Stroke();
                        
                        if (!string.IsNullOrEmpty(pImg64))
                        {
                            iTextSharp.text.Image _imagen = iTextSharp.text.Image.GetInstance(ConvertStringBase64ToImage(oFirmaElectronicaModel.oFirmaElectronica.SIGSTRING_64));
                            _imagen.Border = iTextSharp.text.Rectangle.NO_BORDER;
                            _imagen.BorderColor = iTextSharp.text.Color.WHITE;
                            _imagen.SetAbsolutePosition(385.5f, 55.8f);
                            _imagen.ScaleToFit(150f, 81.5f);

                            oDocument.Add(_imagen);
                        }
                        oDocument.Close();
                        b_Resultado = true;
                    }
                        #endregion
                
            }
            catch (Exception ex) { b_Resultado = false; }
            //
            return b_Resultado;
        }
        private iTextSharp.text.Table Obtener_Logos(System.Web.UI.Page pPage)
        {
            iTextSharp.text.Table tbLogos = null;
            iTextSharp.text.Cell tdCell = null;
            iTextSharp.text.Image oFinancieraUno = null;
            iTextSharp.text.Image oOechsle = null;
            // Tabla
            tbLogos = new iTextSharp.text.Table(3);
            tbLogos.Width = 90;
            tbLogos.Cellpadding = 1;
            tbLogos.Cellspacing = 0;
            tbLogos.Border = iTextSharp.text.Rectangle.NO_BORDER;
            //
            if (pPage == null)
            {
                oFinancieraUno = iTextSharp.text.Image.GetInstance(string.Concat(System.Web.Hosting.HostingEnvironment.MapPath("~/Imagen/"), "Logo_ESSolutions.jpg"));
            }
            else
            {
                oFinancieraUno = iTextSharp.text.Image.GetInstance(string.Concat(pPage.Server.MapPath("~/Imagen/"), "Logo_ESSolutions.jpg"));
            }
            oFinancieraUno.ScaleAbsolute(300, 90);
            tdCell = new iTextSharp.text.Cell();
            tdCell.HorizontalAlignment = iTextSharp.text.Element.ALIGN_CENTER;
            tdCell.VerticalAlignment = iTextSharp.text.Element.ALIGN_MIDDLE;
            tdCell.Border = iTextSharp.text.Rectangle.NO_BORDER;
            tdCell.Add(oFinancieraUno);
            tbLogos.AddCell(tdCell);
            //
            tdCell = new iTextSharp.text.Cell(String.Empty);
            tdCell.Border = iTextSharp.text.Rectangle.NO_BORDER;
            tbLogos.AddCell(tdCell);
            //
            if (pPage == null)
            {
                oOechsle = iTextSharp.text.Image.GetInstance(string.Concat(System.Web.Hosting.HostingEnvironment.MapPath("~/Imagen/"), "Logo_ESSolutions.jpg"));
            }
            else
            {
                oOechsle = iTextSharp.text.Image.GetInstance(string.Concat(pPage.Server.MapPath("~/Imagen/"), "Logo_ESSolutions.jpg"));
            }
            oOechsle.ScaleAbsolute(65, 45);
            tdCell = new iTextSharp.text.Cell();
            tdCell.HorizontalAlignment = iTextSharp.text.Element.ALIGN_RIGHT;
            tdCell.VerticalAlignment = iTextSharp.text.Element.ALIGN_TOP;
            tdCell.Border = iTextSharp.text.Rectangle.NO_BORDER;
            tdCell.Add(oOechsle);
            tbLogos.AddCell(tdCell);
            //
            return tbLogos;
        }

        private iTextSharp.text.Table Obtener_Titulo(String pNro_Solicitud)
        {
            iTextSharp.text.Table tbTitulo = null;
            iTextSharp.text.Cell tdCell = null;
            iTextSharp.text.Chunk oChunk = null;
            // Tabla
            tbTitulo = new iTextSharp.text.Table(1);
            tbTitulo.Width = 90;
            tbTitulo.Cellpadding = 1;
            tbTitulo.Cellspacing = 0;
            tbTitulo.Border = iTextSharp.text.Rectangle.NO_BORDER;
            // Texto
            oChunk = new iTextSharp.text.Chunk("SOLICITUD DE ATENCIÓN MÚLTIPLE", iTextSharp.text.FontFactory.GetFont(iTextSharp.text.FontFactory.HELVETICA, 12, iTextSharp.text.Font.BOLD, new iTextSharp.text.Color(0, 0, 0)));
            // Celda > Título
            tdCell = new iTextSharp.text.Cell(oChunk);
            tdCell.Header = false;

E-FirmaElect-Demo/Views/FirmaElectronica/Index.cshtml
@model E_FirmaElect_Demo.Models.FirmaElectronicaModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script type="text/javascript">
var tmr;

function onSign()
{
   var ctx = document.getElementById('cnv').getContext('2d');
   SetDisplayXSize( 500 );
   SetDisplayYSize( 100 );
   SetTabletState(0, tmr);
   SetJustifyMode(0);
   ClearTablet();
   if(tmr == null)
   {
      tmr = SetTabletState(1, ctx, 50);
   }
   else
   {
      SetTabletState(0, tmr);
      tmr = null;
      tmr = SetTabletState(1, ctx, 50);
   }
}

function onClear()
{
   ClearTablet();
}

function onDone()
{
   if(NumberOfTabletPoints() == 0)
   {
      alert("Please sign before continuing");
   }
   else
   {
      SetTabletState(0, tmr);
      //RETURN TOPAZ-FORMAT SIGSTRING
      SetSigCompressionMode(0);
      $('#bioSigData').val(GetSigString());
      $('#sigStringData').val(GetSigString());
      //document.formDemoFirma.bioSigData.value = GetSigString();
      //document.formDemoFirma.sigStringData.value += GetSigString();
      //this returns the signature in Topaz's own format, with biometric information


      //RETURN BMP BYTE ARRAY CONVERTED TO BASE64 STRING
      SetImageXSize(500);
      SetImageYSize(100);
      SetImagePenWidth(5);
      GetSigImageB64(SigImageCallback);
   }
}

function SigImageCallback( str )
{
    $('#sigImageData').val(str);
    //document.formDemoFirma.sigImageData.value = str;
}


    </script>


<script type="text/javascript">
    window.onunload = window.onbeforeunload = (function () {
        closingSigWeb()
    })
    $(document).ready(function () {
        $( "#@Html.IdFor(model => model.oPersona.DNI)" ).blur(function() {
            var urlXML = '@Url.Action("Obtener_Archivo_Validado", "FirmaElectronica", new { pSigString = "_pSigString", pNum_DNI="_DNI" })'.replace('_pSigString', $('#@Html.IdFor(model => model.oFirmaElectronica.SIGSTRING_ENCRIPTADA)').val()).replace('_pNum_DNI', $('#@Html.IdFor(model => model.oPersona.DNI)').val()).replace('amp;', '');

            $("#btnVerificarPDF").attr("href", urlXML);
        });
        $( "#@Html.IdFor(model => model.oFirmaElectronica.SIGSTRING_ENCRIPTADA)" ).blur(function() {
            var urlXML = '@Url.Action("Obtener_Archivo_Validado", "FirmaElectronica", new { pSigString = "_pSigString", pNum_DNI = "_pNum_DNI" })'.replace('_pSigString', $('#@Html.IdFor(model => model.oFirmaElectronica.SIGSTRING_ENCRIPTADA)').val()).replace('_pNum_DNI', $('#@Html.IdFor(model => model.oPersona.DNI)').val()).replace('amp;', '');

            $("#btnVerificarPDF").attr("href", urlXML);
        });
        $("#btngenerar").click(function (e) {
            e.preventDefault
            $('#@Html.IdFor(m=> m.oFirmaElectronica.SIGSTRING)').val($('#sigStringData').val());
            $('#@Html.IdFor(m=> m.oFirmaElectronica.SIGSTRING_64)').val($('#sigImageData').val());

            var fc_summit = function ()
            {
                var data = null;
                data = new FormData($("#formDemoFirma").get(0));

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Index", "FirmaElectronica")',
                    dataType: 'json',
                    data: data,//{ arg: JSON.stringify(value) },
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        if (data.Resultado == 'Ok') {
                            $('#@Html.IdFor(model => model.oFirmaElectronica.SIGSTRING_ENCRIPTADA)').val(data.oFirmaElectronica.SIGSTRING_ENCRIPTADA);
                            var urlXML = '@Url.Action("Obtener_Archivo_Validado", "FirmaElectronica", new { pSigString = "_pSigString", pNum_DNI = "_pNum_DNI" })'.replace('_pSigString', $('#@Html.IdFor(model => model.oFirmaElectronica.SIGSTRING_ENCRIPTADA)').val()).replace('_pNum_DNI', $('#@Html.IdFor(model => model.oPersona.DNI)').val()).replace('amp;', '');

                            $("#btnVerificarPDF").attr("href", urlXML);
                            fc_MensajeBootBoxConfirm('success', "Archivo Firma Electrónica", "Se generó exitosamente el archivo con la firma electrónica", function () { }, function () { });
                        }
                        else {
                            fc_MensajeBootBoxConfirm('waring', "Archivo Firma Electrónica", "Problemas al generar el archivo con firma electrónica", function () { }, function () { });

                        }
                    }
                });
            }
            //Ini E.Z. 16/06/2016

            fc_MensajeBootBoxConfirm('info', "Archivo Firma Electrónica", "Desea generar Archivo con firma electrónica", fc_summit, function () { });
        });
        function closingSigWeb() {
            ClearTablet();
            SetTabletState(0, tmr);
        }

    });
    function onSuccesForm(pResponse) {
        if (pResponse == 'Ok') {
            fc_MensajeBootBoxConfirm('success', "Archivo Firma Electrónica", "Se generó exitosamente el archivo con la firma electrónica", function () { }, function () { });

        }
        else {
            fc_MensajeBootBoxConfirm('waring', "Archivo Firma Electrónica", "Problemas al generar el archivo con firma electrónica", function () { }, function () { });

        }
    }

</script>

 
 
<div class="panel panel-success active" style="padding-top:55px;">
    <div class="panel-heading">
        <div class="row">
            <div class="col-sm-12">
                <label>
                    <i class="glyphicon glyphicon-list-alt"></i> Firma Electronica
                </label>
            </div>
        </div>
    </div>
    @using (Ajax.BeginForm("Index", "FirmaElectronica", new AjaxOptions { OnSuccess = "onSuccesForm", HttpMethod = "POST" }, new { id = "formDemoFirma", @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.oFirmaElectronica.SIGSTRING)
        @Html.HiddenFor(m => m.oFirmaElectronica.SIGSTRING_64)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="panel-body p-t-xxs">
            <div class="form-horizontal">
                <div class="form-group m-b-sm">
                    <div class="col-sm-3">
                        <label class="control-label ">Número Documento</label>
                        <div class="input-group">
                            <label for="date-picker-3" class="input-group-addon btn">
                                <span class="glyphicon glyphicon-paperclip"></span>
                            </label>
                            @Html.TextBoxFor(model => model.oPersona.DNI,  new { @class = "form-control"    })
                        </div>
                    </div>
                     
                </div>
                <div class="form-group m-b-sm">
                    <div class="col-sm-3">
                        <label class="control-label ">Ape. Paterno</label>
                         
                            @Html.TextBoxFor(model => model.oPersona.APE_PATERNO, new { @class = "form-control" })
                    </div>
                    <div class="col-sm-3">
                        <label class="control-label ">Ape. Materno</label>
                            @Html.TextBoxFor(model => model.oPersona.APE_MATERNO,  new { @class = "form-control" } )
                    </div>
                    <div class="col-sm-3">
                        <label class="control-label ">Pri. Nombre</label>

                        @Html.TextBoxFor(model => model.oPersona.PRI_NOMBRE, new { @class = "form-control" })
                    </div>
                    <div class="col-sm-3">
                        <label class="control-label ">Seg. Nombre</label>
                        @Html.TextBoxFor(model => model.oPersona.SEG_NOMBRE, new { @class = "form-control" })
                    </div>

                </div>

                <div class="form-group m-b-sm">
                    <div class="col-sm-12">
                        <label class="control-label ">Imagen Firma</label>
                        <table border="1" cellpadding="0" width="500">
                            <tr>
                                <td height="100" width="500">
                                    <canvas id="cnv" name="cnv" width="500" height="100"></canvas>
                                </td>
                            </tr>
                        </table>
                        <br />
                        @*<canvas name="SigImg" id="SigImg" width="500" height="100"></canvas>*@
                    </div>

                </div>
                <div class="form-group m-b-sm">
                    <div class="col-sm-7">
                        <input id="SignBtn" name="SignBtn" type="button" value="Firmar" class="btn btn-success" onclick="javascript:onSign()" />&nbsp;&nbsp;&nbsp;&nbsp;
                        <input id="btnLimpiar" name="ClearBtn" type="button" value="Limpiar" class="btn btn-success" onclick="javascript:onClear()" />&nbsp;&nbsp;&nbsp;&nbsp

                        <input id="btnHecho" name="DoneBtn" type="button" value="Terminar" class="btn btn-success" onclick="javascript:onDone()" />&nbsp;&nbsp;&nbsp;&nbsp
                        <input id="btngenerar"  type="button" value="Generar PDF" class="btn btn-primary"   />&nbsp;&nbsp;&nbsp;&nbsp

                        <a id="btnVerificarPDF" href="@Url.Action("Obtener_Archivo_Validado", "FirmaElectronica", new { pSigString = "_pSigString", pNum_DNI="_DNI" })" class="btn btn-primary"><i class="fa fa-download"></i>&nbsp;Verificar Autenticidad</a>
                        <input type=HIDDEN id="bioSigData" />
                        <input type=HIDDEN id="sigImgData" />
                        <br />
                        <br />
                        <textarea id="sigStringData" rows="20" cols="50"></textarea>
                        <textarea id="sigImageData" rows="20" cols="50" style="display:none;">Base64 String: </textarea>
                         
                    </div>
                    <div class="col-sm-5">
                        <label class="control-label ">Sig String Encriptada</label>
                        @Html.TextAreaFor(model => model.oFirmaElectronica.SIGSTRING_ENCRIPTADA, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
    }
</div>